export const REQUESTSPERSECOND = 10
export const PROCESSINGWAIT = 60 * 1000
export const RETRIES = 5
export const QUERYLIMIT = 100
export const ACCOUNT_ATTRIBUTES = [
    'EMPLOYEE_ID',
    'LAST_NAME',
    'HREF',
    'E_MAIL',
    'CELLULAR_NUMBER',
    'PHONE_NUMBER',
    'IDENTIFICATION',
    'LOGIN',
    'MANAGER_ID',
    'BEGIN_OF_CONTRACT',
    'END_OF_CONTRACT',
    'PROFIL_ID',
    'LOCATION_ID',
    'LOCATION.LOCATION_CODE',
    'LOCATION.LOCATION_FR',
    'LOCATION.LOCATION_PATH',
    'LOCATION.CITY',
    'DEPARTMENT_ID',
    'DEPARTMENT.DEPARTMENT_CODE',
    'DEPARTMENT.DEPARTMENT_FR',
    'DEPARTMENT.DEPARTMENT_PATH',
    'DEPARTMENT.DEPARTMENT_LABEL',
]
export const CONTRACT_DATES = ['BEGIN_OF_CONTRACT', 'END_OF_CONTRACT']
